
DEBUG = True

APP_VERSION = "0.1.0"
APP_TITLE = "Manage Cloud"
APP_DESCRIPTION = "Manage Cloud using REST API"

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = False
SWAGGER_UI_DOC_EXPANSION = 'list'
SWAGGER_UI_OPERATION_ID = True
ERROR_INCLUDE_MESSAGE = False
BUNDLE_ERRORS = True